server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: interface_name
          uri: http://localhost:8888
          predicates:
            - Path=/api/{segment}
      default-filters:
        - AddResponseHeader=source, kaibai

logging:
  level:
    org.springframework.cloud.gateway: INFO

dubbo:
  application:
    name: api-gateway-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848?username=nacos&password=nacos