spring:
  application:
    name: api-service
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.100:3306/api_service
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: none
  # redis 配置
  redis:
    port: 6379
    host: 192.168.31.100
    database: 0
    password: 123456
  mail:
    host: smtp.163.com
    username: wangzz2022@163.com
    password: MOQQPMBZYFUFXXHC #开启POP3之后设置的客户端授权码
    protocol: smtp
    default-encoding: UTF-8
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


dubbo:
  application:
    name: api-server-backend-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848?username=nacos&password=nacos

verify:
  code:
    email: 300 # 邮箱验证码默认有效期时间
    phone: 600 # 手机验证码默认有效期时间